python evaluation.py \
--wandb_project raymondl/gpt2-small \
--filter_runs_by_name relu_sparsity_coeff_30 \
--n_eval_samples 5000 \
--num_neurons 50 \
--num_features_to_explain 10 \
--window_size 64 \
--generate_explanations \
--save_activation_data \
--stratified_calibration \
--calibration_buckets 5 \
--examples_per_bucket 20 \
--multi_bucket_explanations \
--sae_position blocks.8.hook_resid_pre \
--output_path "./artifacts/calibration_gpt2_relu_30_multi" \
--skip_upload